### ISSUE TITLE
Add DB support

### ISSUE THREAD

**Issue by x9nico** [AlonsoAliaga/AlonsoLeaderboards#1]
NOTICE THAT THIS IS JUST A REQUEST. FEATURE CAN NEVER BE ADDED.

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Support MySQL to have LeaderBoards in my DB, with that, I can create a leadeboard on my website with DB of the plugin :)

**Comment by AlonsoAliaga** [comment]
This is a simple API to create leaderboards in-game, there aren't plans to add DB support.
It was originally created so I didn't have to code a complete leaderboard system for my future minigames.

Database support won't be implemented, data must be supplied by the plugin that adds the leaderboard since thats the main purpose of this plugin
