### ISSUE TITLE
NPCs arent syncing

### ISSUE THREAD

**Issue by OllieJW** [AlonsoAliaga/AlonsoLeaderboards#3]
**Describe the bug**
The NPCs for the players are not syncing with their values

**To Reproduce**
1. Set up the signs and an NPC
2. Youll see that the NPC for the player stays on number 2 and number 1 when they go from 1->2

**Screenshots**
![image](https://user-images.githubusercontent.com/71931263/107127894-402b1f00-68b1-11eb-9f8d-1e8b6c2e2139.png)

**Important (please complete the following information):**
Java 1.16.5
Latest plugin release

**Comment by AlonsoAliaga** [comment]
Hello, in case you wonder, I haven't tested the plugin in 1.16.5 since I coded it months ago and last update was long ago.
I am currently busy with college classes and I have no time to update this plugin for now, my studies will always be first.

However, I don't see why this happen, code should work correctly for everyone, the only part that could cause that issue is when updating citizens (npc) name, which is handle by my plugin but if it updates or not it doesn't depend on my plugin, probably a rate limit or something.

Try restarting the server and check if that happens again after restart

**Comment by OllieJW** [comment]
Restarting fixed it! Cheers

**Comment by AlonsoAliaga** [comment]
Good to hear! 😄
