### ISSUE TITLE
Task #843206 for AlonsoLeaderboards v1.4-BETA generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [AlonsoAliaga/AlonsoLeaderboards#4]
Hello, it is some days that I have a strange error in console

https://log.mtxserv.com/s0BIl8h#L3333

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
And another problem too..

The plugin doesn't work with the placeholder 

https://www.spigotmc.org/resources/buycraft-expansion-placeholderapi.82261/

%buycraftAPI_recent_name_0%

**Comment by AlonsoAliaga** [comment]
`
[18:22:53] [Server thread/WARN]: [AlonsoLeaderboards] Task #843206 for AlonsoLeaderboards v1.4-BETA generated an exceptio
3334 | java.lang.NullPointerException: null
3335 | at com.walrusone.skywarsreloaded.utilities.placeholders.SWRPlaceholderAPI.onPlaceholderRequest(SWRPlaceholderAPI.java:62) ~[?:?]
`
This issue is not related directly to AlonsoLeaderboards, issue here is that when placeholder is parsed in leaderboards the plugin skywarsreloaded throws an error because of something is null at the time the placeholder is requested (inside skywars plugin) an attempt to fix it could be increasing the delay time in config.yml for parsing to 3 seconds (60 ticks) or even more, as the error is not thrown in alonsoleaderboards code i can't fix that. (In few words this error is thrown when my plugin attempts to parse placeholder from skywars plugin)

About the buycraftAPI placeholder i don't know. This plugin creates leaderbaords BASED ON PLACEHOLDERS that returns a number or decimals. Numbers are like "6546545" and decimals are like "6544.5633" notice the use of the dot, NOT COMMAS, decimals use periods, not commas. I don't know what the placeholder returns, If it does not return a whole number or a decimal with periods, of course it cannot be used. I cannot order letters, I order numbers.

I don't recommend you to use %buycraftAPI_recent_name_0%, as it's NOT player based, I guess it returns the top 0 of donators.
This plugin associate parsed placeholders with the player. If you use a placeholder that ALWAYS returns the same data for all, of course it will not work. If you want to do something like that, you should use a placeholder that returns a value based on player, for example: Money/balance which is associated directly to the player, which means if player joins and parsed placeholder returns he has 50000 and other player has 3000 it will order automatically in decreasing order. In your case you should use a placeholder that returns the amount donated by the player where the placeholder is used/parsed, not global ones as they are most likely the same for all players.

I hope you have understood the explanation, there is nothing I can do to make buycraft expansion placeholders to work, as this plugin is for player leaderboards, placeholders based on players, not in global values, same goes for skyblock islands, factions, guilds, etc. This works with placeholders associated to players only, thats what this plugin does

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Do you know if there is a buycraft placeholder that I can use instead of the expansion that I mentioned?

**Comment by AlonsoAliaga** [comment]
I don't know any sorry. That expansion you mentioned doesn't have any related to players, and I never heard of any that allowed you to get player donation amount

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
ok... this expansion send the player name... I didn't find any other placeholder for buycraft... 
thanks for your answer ... I like alonsoleaderboard.
