### ISSUE TITLE
Lag in the playerquitevent

### ISSUE THREAD

**Issue by thiagogebrimm** [AlonsoAliaga/AlonsoLeaderboards#5]
**Describe the bug**
It seems that alonso is giving players a big lag when logging out, I believe it's because saving in YML, every time a player logs out the MSTP goes up considerably, if you have a way to solve this lag it would be cool.

**Screenshots**
![image](https://user-images.githubusercontent.com/75040244/127419648-7d750e5f-596a-4d5b-84f1-ac0947d77244.png)

**Important (please complete the following information):**
 - Java version: [16]
 - Plugin version: [1.4-BETA]
 - Server version [This server is running Purpur version git-Purpur-1299 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9e63e8f on ver/1.17.1)]

**Comment by AlonsoAliaga** [comment]
Hello, issue has been reported.
Causes:
- Most likely due to the amount of players registered in the file.
A fix for the file will not be implemented.
We are planning to add mysql support to prevent this "lag" issues, however as you probable noticed, i've just started updating my plugins to support 1.17 (with some new features in some of them). For now the only option is deleting the file and let it regenerate again (empty) so players that connects again register the data again (this will help with performance of course)
After mysql is implemented, this shouldn't be an issue anymore.

However, as i'm a one-member team, I'm working in the "easiest" plugins first, after that, moving to the more complex ones (an this is one of those). Please reset your data for now, once the update is released, it will be "fixed".

Sorry for the inconvenience, I cant give an ETA as I don't know how much it will take me to finish my plugins + adding mysql support for this one. Hope you understand
